#!/bin/sh

# 1. Monitor Setup
# Run wlr-randr before other graphical elements to ensure they render on the correct geometry
wlr-randr --output HDMI-A-1 --pos 0,0 --output DVI-D-1 --scale 1.25 --pos 1920,0

# 2. Wallpaper
# -m fill scales the image to fit the screen, cropping as necessary
swaybg -i /home/rdr/Pictures/Wallpapers/wallpapersden.com_night-at-beach-4k_3840x2160.jpg -m fill &

# 3. Status Bar
waybar &